[package]
name = "fractal_renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.29", features = ["rwh_05"] }
wgpu = "22.0"
pollster = "0.3"
encase = "0.10.0"
wgpu_text = "0.9.0"
