[[frames]]
max_iterations = 1
x_pos = -0.6
y_pos = 0
radius = 3.0
color_gradient_shift = 0.95

[[frames]]
max_iterations = 150
x_pos = -0.6
y_pos = 0
radius = 3.0
color_gradient_shift = 0.95

[[frames]]
max_iterations = 150
x_pos = -0.6
y_pos = 0
radius = 1.0
color_gradient_shift = 0.95

[[frames]]
max_iterations = 150
x_pos = -0.75
y_pos = -0.15
radius = 0.05
color_gradient_shift = 0.95

[[frames]]
max_iterations = 150
x_pos = -0.74
y_pos = -0.15
radius = 0.025
color_gradient_shift = 0.95

[[frames]]
max_iterations = 150
x_pos = -0.74
y_pos = -0.15
radius = 0.003
color_gradient_shift = 0.95

[[frames]]
max_iterations = 512
x_pos = -0.74
y_pos = -0.15
radius = 0.003
color_gradient_shift = 0.95

[[frames]]
max_iterations = 512
x_pos = -0.74
y_pos = -0.15
radius = 0.00005
color_gradient_shift = 0.95

[[frames]]
max_iterations = 1024
x_pos = -0.74
y_pos = -0.15
radius = 0.000005
color_gradient_shift = 0.95

[[frames]]
max_iterations = 1024
x_pos = -0.74000045
y_pos = -0.15
radius = 0.00000005
color_gradient_shift = 0.95

[[transitions]]
from_frame = 0
to_frame = 1
interpolation_type = "InOutCubic"
steps = 600

[[transitions]]
from_frame = 1
to_frame = 1
interpolation_type = "Linear"
steps = 60

[[transitions]]
from_frame = 1
to_frame = 2
interpolation_type = "InSine"
steps = 180

[[transitions]]
from_frame = 2
to_frame = 3
interpolation_type = "Linear"
steps = 180

[[transitions]]
from_frame = 3
to_frame = 3
interpolation_type = "Linear"
steps = 60

[[transitions]]
from_frame = 3
to_frame = 4
interpolation_type = "InSine"
steps = 240

[[transitions]]
from_frame = 4
to_frame = 4
interpolation_type = "Linear"
steps = 180

[[transitions]]
from_frame = 4
to_frame = 5
interpolation_type = "InOutCubic"
steps = 240

[[transitions]]
from_frame = 5
to_frame = 5
interpolation_type = "Linear"
steps = 60

[[transitions]]
from_frame = 5
to_frame = 6
interpolation_type = "InOutCubic"
steps = 240

[[transitions]]
from_frame = 6
to_frame = 6
interpolation_type = "Linear"
steps = 60

[[transitions]]
from_frame = 6
to_frame = 7
interpolation_type = "InSine"
steps = 240

[[transitions]]
from_frame = 7
to_frame = 8
interpolation_type = "Linear"
steps = 240

[[transitions]]
from_frame = 8
to_frame = 9
interpolation_type = "InSine"
steps = 240

[[transitions]]
from_frame = 9
to_frame = 9
interpolation_type = "Linear"
steps = 320
